### ISSUE TITLE
Clickable areas in map modal 'drift' versus the actual map the further right/down they are

### ISSUE THREAD

**Issue by apepers** [Roguelike-Celebration/azure-mud#327]
When I use the minimap on Chrome there is progressive mismatch between the ASCII map and the clickable rooms along the x axis. It gets to the point that the leftmost edge of the unconference lobby takes me to the theatre, and I can't get the unconference lobby until I'm at about the o/n on 'unconference'.
Travis tried on the main build and didn't see it, so, who even knows. Low priority since you can use the list as a backup.

**Comment by lazerwalker** [comment]
Are you talking about the full map or the mini-map (which I think now should just open the map instead of letting you select things?)

What would be really helpful is if you can open up the Inspector, find the clickable areas (they're each individual divs that should be aligned) and taking a screenshot of a misaligned one

**Comment by apepers** [comment]
![image](https://user-images.githubusercontent.com/2009311/94980907-23d63a80-04eb-11eb-9f92-654e279eea44.png)
![image](https://user-images.githubusercontent.com/2009311/94980917-2fc1fc80-04eb-11eb-9164-761b15c881b6.png)
![image](https://user-images.githubusercontent.com/2009311/94980923-3cdeeb80-04eb-11eb-9aab-7642adea1a0a.png)

**Comment by apepers** [comment]
I wonder does it possibly just count the width of a character as too wide? It gets worse through the x axis and it seems like right from the start, the width is too big even though I believe the width character count is correct.
![image](https://user-images.githubusercontent.com/2009311/94980942-57b16000-04eb-11eb-995e-a69fbf31e547.png)

**Comment by lazerwalker** [comment]
Cool, this is solvable.

We're not explicitly specifying a font for the map, and since it's a `<pre>` our global preset gets overriden by default to whatever the system monospace font is, which varies from OS to OS.

Manually specifying a font, and then fixing the sizing for that font, should do it. IBM Mono doesn't look great for this, so if I have time I'll find something else.

**Comment by kawa-kitsuragi** [comment]
This definitely happened again in 2021 (I lampshaded it in Oracle). I mentioned it in our Discord at the time but not here, mostly because we were working pretty close to the wire.

![The 'Robot Labs' room, as seen in Chrome Inspector. The clickable region has more space on the right and bottom than intended, but otherwise aligned.](https://user-images.githubusercontent.com/62489292/168704783-4c2aeb34-3cfa-4a6b-90f6-afe050b37f1c.png)

![The 'Skeleton' room's clickable region is nowhere near the relevant room in the map.](https://user-images.githubusercontent.com/62489292/168704846-08650108-d85e-4a86-b49b-b65423d0799b.png)

To my instincts, this feels like a somewhat easy win for someone who can find the relevant CSS for the map modal, but willing to hear otherwise if need be.

**Comment by lazerwalker** [comment]
As an implementation detail, this is going to be a fair bit more complex than just CSS. The clickable areas are generated via manual JS math that calculates grid offsets based on presumed font sizes of each individual character. Either it's as simple as saying "whoops, we said each character was N pixels wide but it's actually N+1", or this is a deep dark pit of sadness.

This ties into #371, but one potential solution would be to move the entire map over to a single static image using an old-school image map. We would still need manual pixel offsets to programmatically insert user counts (and potentially room names, I don't remember if we do that programmatically or in the art), but that might enable a simpler workflow. This map isn't designed to be accessible (it's why we provide the list of rooms as a fallback) so I don't think we'd necessarily lose much from having the text not be highlightable.
