### ISSUE TITLE
Can use custom emoji

### ISSUE THREAD

**Issue by lazerwalker** [Roguelike-Celebration/azure-mud#66]
An extension of #19 

This will need to happen on the server/at rendering instead of at input-time. Presumably if the user types `:poggers:` or `:swartzcr:` or whatever, that will be sent to the server. Either at the time of client-side rendering or at the time the server sends out the SignalR messages with the chat content to other players, we'll then need to replace that text with an HTML `<img>` tag.

I've actually handled this in the past with an app that consumed Slack's API.
the conversion: https://github.com/lazerwalker/xoxo-closing-party/blob/master/messages/index.js#L40-L70
the data file: https://github.com/lazerwalker/xoxo-closing-party/blob/master/messages/emoji.js

**Comment by lazerwalker** [comment]
[This should be an entirely client-side issue. Let me know if you want to work on this, and I can find a few custom emoji to use as test cases.

The simplest version of this: let's say we have a `:spelunky_pug:` emoji that renders the pug you can save in Spelunky. If you type `:spelunky_pug:` into the chat input box, nothing changes while you are typing. But when that message is rendered in the chat view, that string is replaced by an HTML image tag that renders the Spelunky pug image.

I think the correct way to do this is to have some code that swaps out colon-emoji for custom emoji (see the above lazerwalker/xoxo-closing-party code links for a working example) that runs on the client-side when rendering MessageViews. If this runs on the server, then we'll need to render messages as raw HTML from the server, which opens a can of worms. But feel free to discuss.

A more complicated version involves working with #84 to provide emoji picker support for our custom emoji.

**Comment by lazerwalker** [comment]
This would be a cute way to allow us to support community culture. Doing this first requires design work to actually figure out what custom emoji would matter to the community.

**Comment by lazerwalker** [comment]
This will likely be important for #591

**Comment by rmkubik** [comment]
It looks like we're already using `node-emoji` to convert :short_codes: to emoji already in this project. It seems like we're using it in `InputView` which is a component on our profile page. I'm inclined to continue to use that versus port the custom implementation from the xoxo code base. 

Or, if we'd prefer to move off `node-emoji` I could convert the `InputView` to use the ported logic instead.

**Comment by rmkubik** [comment]
Ah, `InputView` is also where the player types their message. This is interesting, we're actually converting their shortcode INTO the unicode emoji value. We probably want to continue to display this visually, but not actually transform the data itself from the short code.

**Comment by lazerwalker** [comment]
No strong opinion on `node-emoji` vs `InputView`! Happy to go with your inclination.

Good catch on keeping the raw untransformed data. Maybe worth checking in with @MoyTW, he's got username @-tagging on a branch that should be also dealing with `InputView` rendering something different than the representation we're sending to the server

**Comment by rmkubik** [comment]
I've chatted with @MoyTW about how #615 conflicts with this PR since both need to touch the `InputView` component.

I did some research on how `react-mentions` (the library #615 uses) and custom emoji might work together.

## What I investigated
- I thought maybe we could use `react-mentions` where `:` is the `Mention` trigger. 
- `react-mentions` doesn't seem to let me use a different `className` to style those mentions differently for the different `Mention` children, both just get the same class as the first `Mention`.
  - Meaning I don't think we could style "user mentions" differently than "emoji mentions". 
- If it did, I'm not sure it'd let us style an image overtop of the text any way since it still seems to put the text

## Solutions

### Leave custom emoji as plain text
We could consider leaving `:custom_emoji:` as text and only expanding it to the image in the chat window?

### Use a rich text editor library
Otherwise, I think we'd need to look into something like [slate.js](https://docs.slatejs.org/), which does seem to suggest it supports both mentions and embeddable images. (and according to inspect element seems to be what Discord is using under the hood.)

A potential drawback of this direction is that it intends to support "full rich text" which is way more functionality than we need. My main concern here would be over-complicating the project, followed by inflating the bundle size (I'm not sure how well we wrangle that currently).

## Thoughts?
Switching to a rich text editor seems like a pretty drastic re-work of #615 though, so maybe the "leave it in plain text while in the textbox" works for now? Would love to hear others' thoughts before picking a direction!

**Comment by lazerwalker** [comment]
I'm open to other thoughts, but my gut is that leaving things in plain text in the editor is fine? If that becomes a huge pain point in the preview event or 2022 event, that sounds like a great signal to invest then in a more custom rich text input box.

**Comment by MoyTW** [comment]
Agree leaving as plain text is fine but if we do that we might want to switch the non-custom emoji over to plain text?

Probably "however Twitch does it" is a good guide but I don't actually know how Twitch does it.

**Comment by rmkubik** [comment]
I think we accomplished this with #626?

**Comment by lazerwalker** [comment]
Agreed!
